Restart docker more defensively

diff --git a/bin/travis-worker-install b/bin/travis-worker-install
--- a/bin/travis-worker-install
+++ b/bin/travis-worker-install
@@ -205,7 +205,8 @@ __install_docker_version_with_options() {
     docker_opts="$docker_opts --storage-driver=aufs --icc=false"
     docker_opts="$docker_opts $docker_version_options $docker_mount_point"
     echo "DOCKER_OPTS=\"$docker_opts\"" >> $DOCKER_CONFIG_FILE
-    restart docker
+    service docker stop || { echo "Failed to stop docker (exit $?)" }
+    service docker start || { echo "Failed to start docker (exit $?)" }
     sleep 2
   fi
 }
