Switch to official docker client library
plus `shfmt` updates.

Closes #351

diff --git a/bin/travis-worker-install b/bin/travis-worker-install
--- a/bin/travis-worker-install
+++ b/bin/travis-worker-install
@@ -14,82 +14,82 @@ main() {
 
   while [ $# -gt 0 ]; do
     case "$1" in
-      --aws=* | --aws)
-        AWS="${1#*=}"
-        : "${AWS:=true}"
-        export AWS
-        ;;
-      --docker[-_]apt[-_]file=*)
-        export DOCKER_APT_FILE="${1#*=}"
-        ;;
-      --docker[-_]cmd=*)
-        export DOCKER_CMD="${1#*=}"
-        ;;
-      --docker[-_]config[-_]file=*)
-        export DOCKER_CONFIG_FILE="${1#*=}"
-        ;;
-      --docker[-_]image[-_]language[-_]mappings=*)
-        export DOCKER_IMAGE_LANGUAGE_MAPPINGS="${1#*=}"
-        ;;
-      --docker[-_]image[-_]languages=*)
-        export DOCKER_IMAGE_LANGUAGES="${1#*=}"
-        ;;
-      --stable)
-        export INSTALL_MODE=stable
-        export PACKAGECLOUD_SOURCE='travisci/worker'
-        ;;
-      --edge)
-        export INSTALL_MODE=edge
-        export PACKAGECLOUD_SOURCE='travisci/worker-testing'
-        ;;
-      --enterprise)
-        export TRAVIS_ENTERPRISE=1
-        ;;
-      --docker[-_]install[-_]mode=*)
-        export INSTALL_MODE="${1#*=}"
-        ;;
-      --packagecloud[-_]source=*)
-        export PACKAGECLOUD_SOURCE="${1#*=}"
-        ;;
-      --skip[-_]docker[-_]populate=* | --skip[-_]docker[-_]populate)
-        SKIP_DOCKER_POPULATE="${1#*=}"
-        : "${SKIP_DOCKER_POPULATE:=true}"
-        export SKIP_DOCKER_POPULATE
-        ;;
-      --trace)
-        set -o xtrace
-        ;;
-      --travis[-_]enterprise[-_]build[-_]endpoint=*)
-        export TRAVIS_ENTERPRISE_BUILD_ENDPOINT="${1#*=}"
-        export TRAVIS_ENTERPRISE=1
-        ;;
-      --travis[-_]enterprise[-_]config=*)
-        export TRAVIS_ENTERPRISE_CONFIG="${1#*=}"
-        export TRAVIS_ENTERPRISE=1
-        ;;
-      --travis[-_]enterprise[-_]host=*)
-        export TRAVIS_ENTERPRISE_HOST="${1#*=}"
-        export TRAVIS_ENTERPRISE=1
-        ;;
-      --travis[-_]enterprise[-_]security[-_]token=*)
-        export TRAVIS_ENTERPRISE_SECURITY_TOKEN="${1#*=}"
-        export TRAVIS_ENTERPRISE=1
-        ;;
-      --travis[-_]queue[-_]name=*)
-        export TRAVIS_QUEUE_NAME="${1#*=}"
-        ;;
-      --travis[-_]worker[-_]version=*)
-        export TRAVIS_WORKER_VERSION="${1#*=}"
-        ;;
-      -h | --help | help)
-        __help
-        exit 0
-        ;;
-      *)
-        echo "Error: Invalid argument '$1'" >&2
-        __help
-        exit 1
-        ;;
+    --aws=* | --aws)
+      AWS="${1#*=}"
+      : "${AWS:=true}"
+      export AWS
+      ;;
+    --docker[-_]apt[-_]file=*)
+      export DOCKER_APT_FILE="${1#*=}"
+      ;;
+    --docker[-_]cmd=*)
+      export DOCKER_CMD="${1#*=}"
+      ;;
+    --docker[-_]config[-_]file=*)
+      export DOCKER_CONFIG_FILE="${1#*=}"
+      ;;
+    --docker[-_]image[-_]language[-_]mappings=*)
+      export DOCKER_IMAGE_LANGUAGE_MAPPINGS="${1#*=}"
+      ;;
+    --docker[-_]image[-_]languages=*)
+      export DOCKER_IMAGE_LANGUAGES="${1#*=}"
+      ;;
+    --stable)
+      export INSTALL_MODE=stable
+      export PACKAGECLOUD_SOURCE='travisci/worker'
+      ;;
+    --edge)
+      export INSTALL_MODE=edge
+      export PACKAGECLOUD_SOURCE='travisci/worker-testing'
+      ;;
+    --enterprise)
+      export TRAVIS_ENTERPRISE=1
+      ;;
+    --docker[-_]install[-_]mode=*)
+      export INSTALL_MODE="${1#*=}"
+      ;;
+    --packagecloud[-_]source=*)
+      export PACKAGECLOUD_SOURCE="${1#*=}"
+      ;;
+    --skip[-_]docker[-_]populate=* | --skip[-_]docker[-_]populate)
+      SKIP_DOCKER_POPULATE="${1#*=}"
+      : "${SKIP_DOCKER_POPULATE:=true}"
+      export SKIP_DOCKER_POPULATE
+      ;;
+    --trace)
+      set -o xtrace
+      ;;
+    --travis[-_]enterprise[-_]build[-_]endpoint=*)
+      export TRAVIS_ENTERPRISE_BUILD_ENDPOINT="${1#*=}"
+      export TRAVIS_ENTERPRISE=1
+      ;;
+    --travis[-_]enterprise[-_]config=*)
+      export TRAVIS_ENTERPRISE_CONFIG="${1#*=}"
+      export TRAVIS_ENTERPRISE=1
+      ;;
+    --travis[-_]enterprise[-_]host=*)
+      export TRAVIS_ENTERPRISE_HOST="${1#*=}"
+      export TRAVIS_ENTERPRISE=1
+      ;;
+    --travis[-_]enterprise[-_]security[-_]token=*)
+      export TRAVIS_ENTERPRISE_SECURITY_TOKEN="${1#*=}"
+      export TRAVIS_ENTERPRISE=1
+      ;;
+    --travis[-_]queue[-_]name=*)
+      export TRAVIS_QUEUE_NAME="${1#*=}"
+      ;;
+    --travis[-_]worker[-_]version=*)
+      export TRAVIS_WORKER_VERSION="${1#*=}"
+      ;;
+    -h | --help | help)
+      __help
+      exit 0
+      ;;
+    *)
+      echo "Error: Invalid argument '$1'" >&2
+      __help
+      exit 1
+      ;;
     esac
     shift
   done
