More adjustments to docker version check and messaging

diff --git a/utils/smoke-package b/utils/smoke-package
--- a/utils/smoke-package
+++ b/utils/smoke-package
@@ -27,6 +27,7 @@ main() {
     echo "     ERROR: unexpected docker server version" >&2
     echo "     ERROR:   expected: 1.12.[0-9]" >&2
     echo "     ERROR:     actual: ${docker_version}" >&2
+    docker version
     exit 1
   fi
 
@@ -59,8 +60,9 @@ main() {
   )"
   if [[ ! "${docker_version}" =~ 1\.7\.[0-9] ]]; then
     echo "     ERROR: unexpected docker server version" >&2
-    echo "     ERROR:   expected: 1.12.[0-9]" >&2
+    echo "     ERROR:   expected: 1.7.[0-9]" >&2
     echo "     ERROR:     actual: ${docker_version}" >&2
+    docker version
     exit 1
   fi
 
