Add some verbosity to docker version checks

diff --git a/utils/smoke-package b/utils/smoke-package
--- a/utils/smoke-package
+++ b/utils/smoke-package
@@ -20,9 +20,13 @@ main() {
   ${sudo_exe} ./bin/travis-worker-install --trace --skip-docker-populate --edge
 
   /usr/local/bin/travis-worker --version
-  docker version | if ! grep -qE '1\.12\.\d' ; then
-    echo '     ERROR: unexpected docker version' >&2
-    docker version
+
+  local docker_version
+  docker_version="$(docker version --format '{{.Server.Version}}')"
+  if [[ ! "${docker_version}" =~ 1\.12\.[0-9] ]]; then
+    echo "     ERROR: unexpected docker server version" >&2
+    echo "     ERROR:   expected: 1.12.[0-9]" >&2
+    docker version --format '{{.Server.Version}}'
     exit 1
   fi
 
@@ -47,10 +51,12 @@ main() {
   echo '---> Installing travis-worker stable'
   ${sudo_exe} ./bin/travis-worker-install --skip-docker-populate --stable
 
-  /usr/local/bin/travis-worker --version
-  docker version | if ! grep -q '1.7.1' ; then
-    echo '     ERROR: unexpected docker version' >&2
-    docker version
+  local docker_version
+  docker_version="$(docker version --format '{{.Server.Version}}')"
+  if [[ ! "${docker_version}" =~ 1\.7\.[0-9] ]]; then
+    echo "     ERROR: unexpected docker server version" >&2
+    echo "     ERROR:   expected: 1.12.[0-9]" >&2
+    docker version --format '{{.Server.Version}}'
     exit 1
   fi
 
