Fetch docker version in a way that's compatible with 1.7.x

diff --git a/utils/smoke-package b/utils/smoke-package
--- a/utils/smoke-package
+++ b/utils/smoke-package
@@ -26,7 +26,7 @@ main() {
   if [[ ! "${docker_version}" =~ 1\.12\.[0-9] ]]; then
     echo "     ERROR: unexpected docker server version" >&2
     echo "     ERROR:   expected: 1.12.[0-9]" >&2
-    docker version --format '{{.Server.Version}}'
+    echo "     ERROR:     actual: ${docker_version}" >&2
     exit 1
   fi
 
@@ -52,11 +52,15 @@ main() {
   ${sudo_exe} ./bin/travis-worker-install --skip-docker-populate --stable
 
   local docker_version
-  docker_version="$(docker version --format '{{.Server.Version}}')"
+  docker_version="$(
+    docker version \
+      | grep -A1 ^Server \
+      | awk '/Version/ { print $2 }'
+  )"
   if [[ ! "${docker_version}" =~ 1\.7\.[0-9] ]]; then
     echo "     ERROR: unexpected docker server version" >&2
     echo "     ERROR:   expected: 1.12.[0-9]" >&2
-    docker version --format '{{.Server.Version}}'
+    echo "     ERROR:     actual: ${docker_version}" >&2
     exit 1
   fi
 
